apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.azure.com/ingress-host: myapp.kubebox.in
    kubernetes.azure.com/tls-cert-keyvault-uri: myapp
  creationTimestamp: null
  name: myapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp
  type: ClusterIP
status:
  loadBalancer: {}
